### ISSUE TITLE
topic of "/monocular_person_following/features"  has no output

### ISSUE THREAD

**Issue by LJH0710** [koide3/monocular_person_following#12]
Hi @koide3 
When I  use "roslaunch monocular_person_following jetson_person_following" , I cannot get the feature image in the rviz, when I use "rostopic echo /monocular_person_following/feature" to show the topic, there is no output. 
Do you have any idea about this?
![2021-06-09 19-22-47 的屏幕截图](https://user-images.githubusercontent.com/69422346/121347385-b459fa00-c959-11eb-8b6b-7c77fe03ed01.png)
![2021-06-09 19-23-47 的屏幕截图](https://user-images.githubusercontent.com/69422346/121347400-bcb23500-c959-11eb-8f5b-aafef9f199de.png)

**Comment by Mavericky-j** [comment]
have you solved? I meet same problem.
