### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by bill4u** [koide3/monocular_person_following#13]
Hello koide, thanks for your great work. I try to install this project from source on Xavier NX/Jetpack 4.5
When I install the tensorflow with the default command: 
sudo pip install -U --extra-index-url https://developer.download.nvidia.com/compute/redist/jp33 tensorflow-gpu
when I import the tensorflow, it prints that the cuda version is not compatible as In Jetpack 4.5 the cuda version is 10.2.

So my question is how to install the right version of tensorflow in order to run this project?
Thanks again for your greak work, like hdl_graph_slam and others hdl_xx_xx which really help me a lot!!

**Comment by bill4u** [comment]
@koide3 Any suggestions?

**Comment by koide3** [comment]
Hi @bill4u ,
I expect the package can run on the latest tensorflow 1.x ([NVIDIA's official instruction](https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html) would be a help for installation), but I'm not 100% sure because it's been a few years and many things (Jetpack/Ubuntu/tensorflow versions) had changed since I released this package...

I'm now checking if the package can be built on the latest Jetpack, and I would update the installation instruction in a few days.

**Comment by bill4u** [comment]
> Hi @bill4u ,
> I expect the package can run on the latest tensorflow 1.x ([NVIDIA's official instruction](https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html) would be a help for installation), but I'm not 100% sure because it's been a few years and many things (Jetpack/Ubuntu/tensorflow versions) had changed since I released this package...
> 
> I'm now checking if the package can be built on the latest Jetpack, and I would update the installation instruction in a few days.

Wow! Thanks koide! Thank you very much!!

**Comment by koide3** [comment]
I updated the installation instruction for Jetpack 4.5.1. But, it requires to build and install ROS noetic from source and takes a few hours. To avoid the painful installation, I recommend using docker image (```koide3/monocular_person_following:jp45```) for a quick test:

https://github.com/koide3/monocular_person_following/wiki/%5BJetpack-4.5%5D-Install-from-source
https://github.com/koide3/monocular_person_following/wiki/%5BJetpack-4.5%5D-Quick-test-on-Jetson-Xavier-with-USB-cam

**Comment by bill4u** [comment]
@koide3 ,HI, koide. I try to use the docker image while something else happened.

`jp45: Pulling from koide3/monocular_person_following
04da93b342eb: Pulling fs layer 
b235194751de: Pulling fs layer 
606a67bb8db9: Pulling fs layer 
9ce7ce1da17c: Pulling fs layer 
f5299db1221c: Pulling fs layer 
cb893097de39: Waiting 
a36863a728ec: Waiting 
86dd6e5994e2: Waiting 
15a5811e1a7b: Waiting 
b1cdeb9e69c9: Waiting 
f0f57d03cad8: Waiting 
f84ceb6e8887: Waiting 
905b1329c1d4: Pulling fs layer 
cfb2938be99f: Waiting 
bf60857fb496: Waiting 
0aac5305d11a: Waiting 
08c23323368d: Waiting 
93752947af53: Waiting 
73272ef679c6: Waiting 
f9cb61931d7a: Waiting 
0506b0abec9f: Waiting 
3af6efd2f585: Waiting 
30de1dd69a7e: Waiting 
d6d873aa93a2: Waiting 
afbaddf7fd32: Waiting 
1d4ba4fe01d3: Waiting 
961c75ddd1ec: Waiting 
16f86189e7a0: Waiting 
fadce42c48e3: Waiting 
1ca58dc429d7: Waiting 
3fb7ecc37da4: Waiting 
820cbb57fca3: Waiting 
ca02328f3991: Pull complete 
b43f88d6ecc2: Pull complete 
05e7a086255d: Pull complete 
9f0fb3aa074d: Pull complete 
e5c71d9b2a38: Pull complete 
97ec3ff007b0: Pull complete 
76e43376f97f: Pull complete 
d2ea19626d11: Pull complete 
3874874d99cd: Pull complete 
aa678e559e93: Pull complete 
a73c035a5667: Pull complete 
6469d6dec3fe: Pull complete 
fa6da0466cfd: Pull complete 
c4d4fabe09c6: Pull complete 
a61b55d8b05f: Pull complete 
d27279dcca54: Pull complete 
6d9d59af664f: Pull complete 
2fe9eb9646b7: Pull complete 
acc45e34b19c: Pull complete 
eb77946b5d73: Pull complete 
b20e93ef30d1: Pull complete 
7ce9530d5d9e: Pull complete 
948a14dae679: Pull complete 
Digest: sha256:180f9b039f0a552c927ac5255da057c43f4a874b294ec78ff02e9b2c9cf9b17e
Status: Downloaded newer image for koide3/monocular_person_following:jp45
docker.io/koide3/monocular_person_following:jp45
`
And I reinput the command: `sudo docker pull koide3/monocular_person_following:jp45`
The terminal outputs:
`jp45: Pulling from koide3/monocular_person_following
Digest: sha256:180f9b039f0a552c927ac5255da057c43f4a874b294ec78ff02e9b2c9cf9b17e
Status: Image is up to date for koide3/monocular_person_following:jp45
docker.io/koide3/monocular_person_following:jp45`
My platform is Jetson Xavier NX with JP45.

**Comment by koide3** [comment]
It's OK. You successfully pulled the docker image.  Plug a USB cam in your PC, and launch the module:

```bash
sudo docker run -it --rm \
                --net host \
                --device /dev/video0:/dev/video0 \
                -v $(realpath ~/.ros/camera_info):/root/.ros/camera_info \
                koide3/monocular_person_following:jp45 \
                roslaunch monocular_person_following start_robot.launch webcam:=true publish_dummy_frames:=true camera_xyz:="0 0 0.9" camera_rpy:="0 0 0"
```

```bash
sudo docker run -it --rm \
                --net host \
                --gpus all \
                koide3/monocular_person_following:jp45 \
                roslaunch monocular_person_following jetson_person_following.launch camera_name:=/top_front_camera/qhd
```

**Comment by bill4u** [comment]
> It's OK. You successfully pulled the docker image. Plug a USB cam in your PC, and launch the module:
> 
> ```shell
> sudo docker run -it --rm \
>                 --net host \
>                 --device /dev/video0:/dev/video0 \
>                 -v $(realpath ~/.ros/camera_info):/root/.ros/camera_info \
>                 koide3/monocular_person_following:jp45 \
>                 roslaunch monocular_person_following start_robot.launch webcam:=true publish_dummy_frames:=true camera_xyz:="0 0 0.9" camera_rpy:="0 0 0"
> ```
> 
> ```shell
> sudo docker run -it --rm \
>                 --net host \
>                 --gpus all \
>                 koide3/monocular_person_following:jp45 \
>                 roslaunch monocular_person_following jetson_person_following.launch camera_name:=/top_front_camera/qhd
> ```

Thank you koide. I have encounted some difficulties and try to deal with them by myself. So I spend a lot of time to study the docker. I have no idea how to change the parameters in the docker. 
I try to run your command and it prints 

`[mjpeg @ 0x555b46fc5b20] No JPEG data found in image
[ERROR] [1625921278.493886725]: Error while decoding frame.
[ERROR] [1625921278.520422589]: outbuf size mismatch.  pic_size: 3686400 bufsize: 4147200`

**And there is no imgs.**

That means my usb_cam driver cannot run in the format of 
`<param name="image_width" value="1920"/>
<param name="image_height" value="1080"/>`

When I change the parameters to 640x480, the roslaunch usb_cam usb_cam.launch won't print the error msgs and the img can be viewed in the rviz.
So would you mind to add two params(width, height) above in the start_robot.launch for users to change the image format ? 
Thanks a lot!

**Comment by koide3** [comment]
Thanks for reporting the issue. I'll add optional image size arguments the launch file.
