### ISSUE TITLE
Cannot get feature image and MarkerArray in the rviz

### ISSUE THREAD

**Issue by rhan-Lau** [koide3/monocular_person_following#3]
Hi, @koide3. When I test the whole monocular_person_following project, I cannot get the feature image and MarkerArray in the rviz, when I use "rostopic echo /monocular_person_following/feature" to show the topic, it says that the topic does not appear to be published yet. I used to think it is something wrong with the problem of ccf module, but it doesn't changed after the ccf module fixed.
Do you have any idea about this?
Also, it seems like there's some problem in the open_face_recognition module, i'm not sure if that's relevant.
![Screenshot from 2019-10-29 19-48-49](https://user-images.githubusercontent.com/27419908/67855917-67dbf500-fb4e-11e9-9acc-c75f08529f7f.png)

**Comment by rhan-Lau** [comment]
Hi, @koide3 . As a progress, I resetting the "framerate" param in web_camera.launch and now can obtain the skeleton smoothly, as a result, I can get the "MarkerArray" topic. However, there is still no rectangle shows in rviz /visualization_node/visualize and still cannot get the /monocular_person_following/features result. I've try many ways but still got the same results. Could you please give me any advice about these?

**Comment by koide3** [comment]
Hi @rhan-Lau ,
Have you installed open_face_recognition module? and what problem did you see on it?

**Comment by rhan-Lau** [comment]
Hi,  @koide3 . Yes, I installed that module, and I think it might be something wrong with the CMakeList.txt? Cause I didn't see any executable file build after catkin_make.

**Comment by rhan-Lau** [comment]
Hi, @koide3 . Yes, I installed that module, and I think it might be something wrong with the CMakeList.txt? Cause I didn't see any executable file build after catkin_make. Can you please check if the file is complete? Thank you very much for all the kind help.

**Comment by koide3** [comment]
It's OK because that module is written in python and doesn't yield any executables. Can you check if the TF tree is properly set up using rqt_tf_tree?

**Comment by rhan-Lau** [comment]
Hi, @koide3 ,
This is what it looks like using "rosrun rqt_tf_tree rqt_tf_tree", so I guess it means I set it right?
![Screenshot from 2019-10-31 18-00-19](https://user-images.githubusercontent.com/27419908/67937460-9ae2bf00-fc08-11e9-85d1-3ea86f4b5c5f.png)
And as for my problem with open_face_recognition, I keep getting "couldn't find executable" error when I rosrun it.
![Screenshot from 2019-10-31 17-44-30](https://user-images.githubusercontent.com/27419908/67937700-ff9e1980-fc08-11e9-87e7-c66ec7a592f0.png)

**Comment by rhan-Lau** [comment]
Hi, @koide3 ,
This is what it looks like using "rosrun rqt_tf_tree rqt_tf_tree", so I guess it means I set it right?
![Screenshot from 2019-10-31 18-00-19](https://user-images.githubusercontent.com/27419908/67938594-c4044f00-fc0a-11e9-971c-6f81a0f37ca8.png)

And as for my problem with open_face_recognition, I keep getting "couldn't find executable" error when I rosrun it.
$ rosrun open_face_recognition open_face_recognition_node.py
[rosrun] Couldn't find executable named open_face_recognition_node.py below /home/han/catkin_ws/src/open_face_recognition
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /home/han/catkin_ws/src/open_face_recognition/scripts/open_face_recognition_node.py

**Comment by koide3** [comment]
OK, it looks file. Please check if the open_face_recognition_node.py has execution permission with "ls -la"

**Comment by rhan-Lau** [comment]
Yes, this is the problem. I add permissions for the file and problem solved. Really appreciate it. @koide3

**Comment by USTB-WZL** [comment]
Hi, does your usb camera opened in 1920*1080? I tried to using my logitech C270, cannot open it, only work with 640*480, and no person detected.

**Comment by USTB-WZL** [comment]
@rhan-Lau need your help
